version: '3'
services:
    apache:
        build: ./docker/apache
        container_name: home4_apache
        ports:
          - 8082:80
        volumes:
          - ./docker/config/vhosts:/etc/apache2/sites-enabled
          - .:/home/wwwroot/home4
        depends_on:
          - php

    mysql:
        image: mysql
        command: "--default-authentication-plugin=mysql_native_password"
        container_name: home4_mysql
        volumes:
            - ./docker/data/db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: home4
            MYSQL_USER: home4
            MYSQL_PASSWORD: home4

    php:
        build: ./docker/php
        container_name: home4_php
        volumes:
          - .:/home/wwwroot/home4
        environment:
          - maildev_host=home4_maildev
        depends_on:
          - maildev
          - mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: home4_phpmyadmin
        environment:
          PMA_HOST: mysql
          PMA_PORT: 3306
        ports:
            - 8080:80
        links:
            - mysql

    maildev:
        image: djfarrelly/maildev
        container_name: home4_maildev
        ports:
          - 8001:80